### ISSUE TITLE
Request to contribute 

### ISSUE THREAD

**Issue by Pandz18** [mashiyathussain2/Fork_CPP#1]
Hey , I would like to contribute to your repo , can you let me know where I should store the files and if there's a list of programs that you would like to finish first

Cheers

**Comment by mashiyathussain2** [comment]
Hey, @Pandz18 thankyou for the request.
I have updated the README.md. Please have a look. I hope this will help you to solve your issue.

Happy coding!

**Comment by Pandz18** [comment]
Hey sure, thank you very much 

You too
