### ISSUE TITLE
Question about finding element in infinite array

### ISSUE THREAD

**Issue by Pandz18** [mashiyathussain2/Fork_CPP#39]
Hey,
I have a question about your solution for the infinite array.

I have another solution for it.

Assuming the array is an AP we can input size and elements. Then we can take A[0] as 'a' and then d=A[1]-A[0] and then using the AP formula , find n (position of element = n-1).

I can add the solution if you want. What are your thoughts?

**Comment by mashiyathussain2** [comment]
Yes you can implement any other solution for any question. But take in mind about the time complexity. In my solution it takes O(log(position)) time.

**Comment by Pandz18** [comment]
> Yes you can implement any other solution for any question. But take in mind about the time complexity. In my solution it takes O(log(position)) time.

How do I find out the time complexity ?

**Comment by mashiyathussain2** [comment]
Before writing a program we must have to think about time complexity and space complexity. Time complexity is the process of determining total time required towards execution of that algorithm. There are some methods for determining the time complexity of the algorithm like frequency count method and some different methods for recurrence relation. I think you have to do some study on this topic and it will really help you to become a good programmer.
